core/urls.py
from django.urls import path
from core import views as v
import core

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    
]

estoque/urls.py
from django.urls import path

from estoque import views as v

app_name = 'estoque'

urlpatterns = [
    path('', v.estoque_entrada_list, name='estoque_entrada_list'),
    path('<int:pk>', v.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
    path('saida/', v.estoque_saida_list, name='estoque_saida_list'),
    path('saida/<int:pk>', v.estoque_saida_detail, name='estoque_saida_detail'),
    path('saida/add/', v.estoque_saida_add, name='estoque_saida_add'),
]

webstore/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('admin/', admin.site.urls),
]

estoque/models.py
from core.models import TimeStampedModel
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from produto.models import Produto

from estoque.managers import EstoqueEntradaManager, EstoqueSaidaManager

MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)


class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))

    def nf_formated(self):
        return str(self.nf).zfill(3)


class EstoqueEntrada(Estoque):

    objects = EstoqueEntradaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque entrada'
        verbose_name_plural = 'estoque entrada'

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_entrada_detail', kwargs={'pk': self.pk})


class EstoqueSaida(Estoque):

    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque saida'
        verbose_name_plural = 'estoque saida'

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_saida_detail', kwargs={'pk': self.pk})


class EstoqueItens(models.Model):
    estoque = models.ForeignKey(
        Estoque,
        on_delete=models.CASCADE,
        related_name='estoques'
    )
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

estoque/forms.py
from django import forms
from django.forms import fields
from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):

    class Meta:
        model = Estoque
        fields = '__all__'


class EstoqueItensForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'
    
    

estoque/views.py
from django.forms.models import inlineformset_factory
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, resolve_url

from .forms import EstoqueForm, EstoqueItensForm
from .models import (Estoque, EstoqueEntrada, EstoqueItens, EstoqueSaida,
                     Produto)


def estoque_entrada_list(request):
    template_name = 'estoque_entrada_list.html'
    objects = EstoqueEntrada.objects.all()
    context = {
        'object_list': objects
    }
    return render(request, template_name, context)


def estoque_entrada_detail(request, pk):
    template_name = 'estoque_entrada_detail.html'
    obj = EstoqueEntrada.objects.get(pk=pk)
    context = {
        'object': obj
    }
    return render(request, template_name, context)


def dar_baixa_estoque(form):
    # Pega os produtos a partir da instancia do formulario (estoque)
    produtos = form.estoques.all()
    for item in produtos:
        produto = Produto.objects.get(pk=item.produto.pk)
        produto.estoque = item.saldo
        produto.save()
    print("Estoque aualizado com sucesso")


def estoque_entrada_add(request):
    template_name = 'estoque_entrada_form.html'
    estoque_form = Estoque()
    item_estoque_form = inlineformset_factory(
        EstoqueEntrada,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_form(
            request.POST,
            instance=estoque_form,
            prefix='estoque'
        )
        if form.is_valid() and formset.is_valid():
            form = form.save()
            formset.save()
            dar_baixa_estoque(form)
            url = 'estoque:estoque_entrada_detail'
            return HttpResponseRedirect(resolve_url(url, form.pk))
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_form(instance=estoque_form, prefix='estoque')

    context = {'form': form, 'formset': formset}
    return render(request, template_name, context)


def estoque_saida_list(request):
    template_name = 'estoque_saida_list.html'
    objects = EstoqueSaida.objects.all()
    context = {
        'object_list': objects
    }
    return render(request, template_name, context)


def estoque_saida_detail(request, pk):
    template_name = 'estoque_saida_detail.html'
    obj = EstoqueSaida.objects.get(pk=pk)
    context = {
        'object': obj
    }
    return render(request, template_name, context)


def estoque_saida_add(request):
    template_name = 'estoque_saida_form.html'
    estoque_form = Estoque()
    item_estoque_form = inlineformset_factory(
        EstoqueSaida,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_form(
            request.POST,
            instance=estoque_form,
            prefix='estoque'
        )
        if form.is_valid() and formset.is_valid():
            form = form.save()
            formset.save()
            dar_baixa_estoque(form)
            url = 'estoque:estoque_saida_detail'
            return HttpResponseRedirect(resolve_url(url, form.pk))
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_form(instance=estoque_form, prefix='estoque')

    context = {'form': form, 'formset': formset}
    return render(request, template_name, context)

estoque/templates/estoque_entrada_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

<h1>{{ object }}</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{ object.nf_formated }}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{ object.created }}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionário</th>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
        </tbody>
    </table>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

estoque/templates/estoque_entrada_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

    <style>

        span.required:after {
            content: "*";
            color: red;
        }
        .form-control {
            margin: 10px;
        }
    </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>    
    <div class="row">
        <div class="col-sm-12">
            <form method=POST novalidate>
                {% csrf_token %}
                <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Entrada
                </legend>
                <div class="row">
                    <div class="col-sm-6">
                        {% for field in form.visible_fields %}
                            <div class="form-group{% if field.errors %} has-error {% endif %}">
                                <label for="{{ field.id_for_label }}">
                                    {% if field.field.required %}
                                    <span class="required">{{ field.label }} </span>
                                    {% else %}
                                        {{ field.label}}
                                    {% endif %}
                                </label>
                                {% render_field field class="form-control" %}
                                {% for error in field.errors %}
                                <span class="text-muted">{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        {{ formset.management_form }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <legend style="border-bottom: 1px solid #e5e5e5;">Produtos
                        </legend>
                        <div id="estoque" class="form-inline">
                            {% for item_estoque_form in formset %}
                                <div id="item-{{ forloop.counter0}}" class="form-group">
                                    {{ item_estoque_form|bootstrap }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                    <i class="fa fa-plus"></i>Adicionar
                </span>

                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button class="btn btn-primary" value=""Save>
                                <i class="fa fa-floppy-o"></i>
                                Salvar
                            </button>
                            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
                                <i class="fa fa-times"></i>
                                Cancelar
                            </a>
                        </div>

                    </div>
                </div>

            </form>
        </div>
    </div>

{% endblock content %}

{% block js %}

    <script>
        $(document).ready(function() {
            // insere classe no primeiro item do produto

            $('#id_estoque-0-produto').addClass('clProduto');
            $('#id_estoque-0-quantidade').addClass('clQuantidade');
            
            $('#add-item').click(function(ev) {
                ev.preventDefault();
                var count =$('#estoque').children().length;
                var tmplMarkup = $('#item-estoque').html();
                var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                $('div#estoque').append(compiledTmpl);

                // update form count
                $('#id_estoque-TOTAL_FORMS').attr('value', count + 1);

                // some animate to scroll to view our new form
                $('html, body').animate({
                    scrollTop: $("#add-item").position().top - 200
                }, 800);

                $('#id_estoque-' + (count) + '-produto').addClass('clProduto');
                $('#id_estoque-' + (count) + '-quantidade').addClass('clQuantidade');
            });
        });

        let estoque
        let saldo
        let campo
        let campo2
        let quantidade

        $(document).on('change', '.clProduto', function(){
            let self = $(this)
            let pk = $(this).val()
            let url = '/produto/' + pk + '/json/'

            $.ajax({
                url:url,
                type: 'GET',
                success: function(response){
                    estoque = response.data[0].estoque
                    campo = self.attr('id').replace('produto', 'quantidade')
                    // Remover o valor do campo quantidade
                    $('#'+campo).val('')
                },
                error: function(xhr){
                    
                }
            })
        });

        $(document).on('change', '.clQuantidade', function(){
            quantidade = $(this).val();
            saldo = Number(quantidade) + Number(estoque);
            campo = $(this).attr('id').replace('quantidade', 'saldo')
            // Atribui o saldo ao campo 'saldo'
            $('#'+campo).val(saldo)
        });

    </script>

    <script type="text/html" id="item-estoque">
        <div id="item-__prefix__" class="form-group">
            {{ formset.empty_form|bootstrap }}
        </div>
    </script>

{% endblock js%}

estoque/templates/estoque_entrada_list.html
{% extends "base.html" %}


{% block content %}

<h2>Estoque Entrada
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_entrada_add' %}">
            <button class="btn btn-primary">
                <span class="fa fa-plus"></span> Adicionar
            </button>
        </a>
    </span>
</h2>

{% if object_list %}
    <table class="table table-striped">
        <thead>
            <th>Item</th>
            <th>NF</th>
            <th>Data</th>
            <th>Funcionário</th>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                </td>
                <td>{{ object.nf_formated }}</td>
                <td>{{ object.created }}</td>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}

estoque/templates/estoque_saida_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>

<h1>{{ object }}</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{ object.nf_formated }}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{ object.created }}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionário</th>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
        </tbody>
    </table>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

estoque/templates/estoque_saida_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

    <style>

        span.required:after {
            content: "*";
            color: red;
        }
        .form-control {
            margin: 10px;
        }
    </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>    
    <div class="row">
        <div class="col-sm-12">
            <form method=POST novalidate>
                {% csrf_token %}
                <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Saida
                </legend>
                <div class="row">
                    <div class="col-sm-6">
                        {% for field in form.visible_fields %}
                            <div class="form-group{% if field.errors %} has-error {% endif %}">
                                <label for="{{ field.id_for_label }}">
                                    {% if field.field.required %}
                                    <span class="required">{{ field.label }} </span>
                                    {% else %}
                                        {{ field.label}}
                                    {% endif %}
                                </label>
                                {% render_field field class="form-control" %}
                                {% for error in field.errors %}
                                <span class="text-muted">{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        {{ formset.management_form }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <legend style="border-bottom: 1px solid #e5e5e5;">Produtos
                        </legend>
                        <div id="estoque" class="form-inline">
                            {% for item_estoque_form in formset %}
                                <div id="item-{{ forloop.counter0}}" class="form-group">
                                    {{ item_estoque_form|bootstrap }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                    <i class="fa fa-plus"></i>Adicionar
                </span>

                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button class="btn btn-primary" value=""Save>
                                <i class="fa fa-floppy-o"></i>
                                Salvar
                            </button>
                            <a href="{% url 'estoque:estoque_saida_list' %}" class="btn btn-danger">
                                <i class="fa fa-times"></i>
                                Cancelar
                            </a>
                        </div>

                    </div>
                </div>

            </form>
        </div>
    </div>

{% endblock content %}

{% block js %}

    <script>
        $(document).ready(function() {
            // insere classe no primeiro item do produto

            $('#id_estoque-0-produto').addClass('clProduto');
            $('#id_estoque-0-quantidade').addClass('clQuantidade');
            
            $('#add-item').click(function(ev) {
                ev.preventDefault();
                var count =$('#estoque').children().length;
                var tmplMarkup = $('#item-estoque').html();
                var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                $('div#estoque').append(compiledTmpl);

                // update form count
                $('#id_estoque-TOTAL_FORMS').attr('value', count + 1);

                // some animate to scroll to view our new form
                $('html, body').animate({
                    scrollTop: $("#add-item").position().top - 200
                }, 800);

                $('#id_estoque-' + (count) + '-produto').addClass('clProduto');
                $('#id_estoque-' + (count) + '-quantidade').addClass('clQuantidade');
            });
        });

        let estoque
        let saldo
        let campo
        let campo2
        let quantidade

        $(document).on('change', '.clProduto', function(){
            let self = $(this)
            let pk = $(this).val()
            let url = '/produto/' + pk + '/json/'

            $.ajax({
                url:url,
                type: 'GET',
                success: function(response){
                    estoque = response.data[0].estoque
                    campo = self.attr('id').replace('produto', 'quantidade')
                    // Remover o valor do campo quantidade
                    $('#'+campo).val('')
                },
                error: function(xhr){
                    
                }
            })
        });

        $(document).on('change', '.clQuantidade', function(){
            quantidade = $(this).val();
            saldo = Number(estoque) - Number(quantidade);
            preco = Number(quantidade) + 100
            campo = $(this).attr('id').replace('quantidade', 'saldo')
            // Atribui o saldo ao campo 'saldo'
            $('#'+campo).val(saldo)
        });

    </script>

    <script type="text/html" id="item-estoque">
        <div id="item-__prefix__" class="form-group">
            {{ formset.empty_form|bootstrap }}
        </div>
    </script>

{% endblock js%}

estoque/templates/estoque_saida_list.html
{% extends "base.html" %}


{% block content %}

<h2>Estoque Saida
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_saida_add' %}">
            <button class="btn btn-primary">
                <span class="fa fa-plus"></span> Adicionar
            </button>
        </a>
    </span>
</h2>

{% if object_list %}
    <table class="table table-striped">
        <thead>
            <th>Item</th>
            <th>NF</th>
            <th>Data</th>
            <th>Funcionário</th>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                </td>
                <td>{{ object.nf_formated }}</td>
                <td>{{ object.created }}</td>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}